[versions]
ksp = "2.0.0-RC1-1.0.20"
kotlin = "2.0.0-RC1"
ktorfit = "1.14.0"
koin = "3.5.6"
koin-annotations = "1.3.1"
ktor = "2.3.10"
publish = "0.28.0"

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-mpp = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android = { id = "com.android.library", version = "8.2.0" }
android-app = { id = "com.android.application", version = "8.2.0" }
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }

[libraries]
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" }
koin-kspCompiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version = "1.8.0" }
ktorfit = {module = "de.jensklingenberg.ktorfit:ktorfit-lib", version.ref = "ktorfit"}
ktorfit-ksp = {module = "de.jensklingenberg.ktorfit:ktorfit-ksp", version.ref = "ktorfit"}
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.6.0" }
ktor-content = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

[bundles]
ktor = ["ktor-json", "ktor-content", "serialization"]