name: Release
on:
  release:
    types: [released]

jobs:
  build-multiplatform-project:
    environment: release
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        gradle: [8.3]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - id: get_version
        name: Get version
        uses: jannemattila/get-version-from-tag@v3

      - name: Display version
        run: |
          export VERSION=$(echo "${{ steps.get_version.outputs.version }}")
          echo $VERSION
      - name: Build and publish
        shell: bash
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNINGINMEMORYKEY }}
        run: ./gradlew ktorfit-koin:publishAllPublicationsToMavenCentralRepository